var hierarchy =
[
    [ "UnityStandardAssets.Characters.FirstPerson.RigidbodyFirstPersonController.AdvancedSettings", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_rigidbody_first_person_controller_1_1_advanced_settings.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.TiltInput.AxisMapping", "class_unity_standard_assets_1_1_cross_platform_input_1_1_tilt_input_1_1_axis_mapping.html", null ],
    [ "UnityStandardAssets.Utility.CameraRefocus", "class_unity_standard_assets_1_1_utility_1_1_camera_refocus.html", null ],
    [ "CoroutineUtilities", "class_coroutine_utilities.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.Inspector.CrossPlatformInitialize", "class_unity_standard_assets_1_1_cross_platform_input_1_1_inspector_1_1_cross_platform_initialize.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager", "class_unity_standard_assets_1_1_cross_platform_input_1_1_cross_platform_input_manager.html", null ],
    [ "UnityStandardAssets.Utility.CurveControlledBob", "class_unity_standard_assets_1_1_utility_1_1_curve_controlled_bob.html", null ],
    [ "DoxygenConfig", "class_doxygen_config.html", null ],
    [ "DoxyRunner", "class_doxy_runner.html", null ],
    [ "DoxyThreadSafeOutput", "class_doxy_thread_safe_output.html", null ],
    [ "Editor", null, [
      [ "UnityStandardAssets.ImageEffects.AntialiasingEditor", "class_unity_standard_assets_1_1_image_effects_1_1_antialiasing_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.BloomAndFlaresEditor", "class_unity_standard_assets_1_1_image_effects_1_1_bloom_and_flares_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.BloomEditor", "class_unity_standard_assets_1_1_image_effects_1_1_bloom_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.CameraMotionBlurEditor", "class_unity_standard_assets_1_1_image_effects_1_1_camera_motion_blur_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.ColorCorrectionCurvesEditor", "class_unity_standard_assets_1_1_image_effects_1_1_color_correction_curves_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.ColorCorrectionLookupEditor", "class_unity_standard_assets_1_1_image_effects_1_1_color_correction_lookup_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.DepthOfFieldDeprecatedEditor", "class_unity_standard_assets_1_1_image_effects_1_1_depth_of_field_deprecated_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.DepthOfFieldEditor", "class_unity_standard_assets_1_1_image_effects_1_1_depth_of_field_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.EdgeDetectionEditor", "class_unity_standard_assets_1_1_image_effects_1_1_edge_detection_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.NoiseAndGrainEditor", "class_unity_standard_assets_1_1_image_effects_1_1_noise_and_grain_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.SunShaftsEditor", "class_unity_standard_assets_1_1_image_effects_1_1_sun_shafts_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.TonemappingEditor", "class_unity_standard_assets_1_1_image_effects_1_1_tonemapping_editor.html", null ],
      [ "UnityStandardAssets.ImageEffects.VignetteAndChromaticAberrationEditor", "class_unity_standard_assets_1_1_image_effects_1_1_vignette_and_chromatic_aberration_editor.html", null ]
    ] ],
    [ "EditorWindow", null, [
      [ "DoxygenWindow", "class_doxygen_window.html", null ]
    ] ],
    [ "UnityStandardAssets.Utility.TimedObjectActivator.Entries", "class_unity_standard_assets_1_1_utility_1_1_timed_object_activator_1_1_entries.html", null ],
    [ "UnityStandardAssets.Utility.TimedObjectActivator.Entry", "class_unity_standard_assets_1_1_utility_1_1_timed_object_activator_1_1_entry.html", null ],
    [ "UnityStandardAssets.Utility.FOVKick", "class_unity_standard_assets_1_1_utility_1_1_f_o_v_kick.html", null ],
    [ "IBeginDragHandler", null, [
      [ "DragDrop", "class_drag_drop.html", null ],
      [ "DragMe", "class_drag_me.html", null ]
    ] ],
    [ "ICanvasRaycastFilter", null, [
      [ "AlphaButtonClickMask", "class_alpha_button_click_mask.html", null ]
    ] ],
    [ "IDragHandler", null, [
      [ "DragDrop", "class_drag_drop.html", null ],
      [ "DragMe", "class_drag_me.html", null ],
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.Joystick", "class_unity_standard_assets_1_1_cross_platform_input_1_1_joystick.html", null ]
    ] ],
    [ "IDropHandler", null, [
      [ "DropMe", "class_drop_me.html", null ],
      [ "SlotController", "class_slot_controller.html", null ]
    ] ],
    [ "IEndDragHandler", null, [
      [ "DragDrop", "class_drag_drop.html", null ],
      [ "DragMe", "class_drag_me.html", null ]
    ] ],
    [ "UnityStandardAssets.ImageEffects.ImageEffects", "class_unity_standard_assets_1_1_image_effects_1_1_image_effects.html", null ],
    [ "IPointerClickHandler", null, [
      [ "ChangeColor", "class_change_color.html", null ],
      [ "RemoveFromInventory", "class_remove_from_inventory.html", null ]
    ] ],
    [ "IPointerDownHandler", null, [
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.AxisTouchButton", "class_unity_standard_assets_1_1_cross_platform_input_1_1_axis_touch_button.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.Joystick", "class_unity_standard_assets_1_1_cross_platform_input_1_1_joystick.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.TouchPad", "class_unity_standard_assets_1_1_cross_platform_input_1_1_touch_pad.html", null ]
    ] ],
    [ "IPointerEnterHandler", null, [
      [ "DropMe", "class_drop_me.html", null ],
      [ "RemoveFromInventory", "class_remove_from_inventory.html", null ]
    ] ],
    [ "IPointerExitHandler", null, [
      [ "DropMe", "class_drop_me.html", null ],
      [ "RemoveFromInventory", "class_remove_from_inventory.html", null ]
    ] ],
    [ "IPointerUpHandler", null, [
      [ "UnityStandardAssets.CrossPlatformInput.AxisTouchButton", "class_unity_standard_assets_1_1_cross_platform_input_1_1_axis_touch_button.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.Joystick", "class_unity_standard_assets_1_1_cross_platform_input_1_1_joystick.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.TouchPad", "class_unity_standard_assets_1_1_cross_platform_input_1_1_touch_pad.html", null ]
    ] ],
    [ "UnityStandardAssets.Utility.LerpControlledBob", "class_unity_standard_assets_1_1_utility_1_1_lerp_controlled_bob.html", null ],
    [ "MonoBehaviour", null, [
      [ "ActiveStateToggler", "class_active_state_toggler.html", null ],
      [ "AddtoInventory", "class_addto_inventory.html", null ],
      [ "AlphaButtonClickMask", "class_alpha_button_click_mask.html", null ],
      [ "ApplicationManager", "class_application_manager.html", null ],
      [ "BreakFruit", "class_break_fruit.html", null ],
      [ "CameraOrbitScript", "class_camera_orbit_script.html", null ],
      [ "ChangeColor", "class_change_color.html", null ],
      [ "ChestOpen", "class_chest_open.html", null ],
      [ "DoorOpener", "class_door_opener.html", null ],
      [ "DoorOpenLeft", "class_door_open_left.html", null ],
      [ "DragDrop", "class_drag_drop.html", null ],
      [ "DragMe", "class_drag_me.html", null ],
      [ "DragPanel", "class_drag_panel.html", null ],
      [ "DropMe", "class_drop_me.html", null ],
      [ "EventSystemChecker", "class_event_system_checker.html", null ],
      [ "ExitOnClick", "class_exit_on_click.html", null ],
      [ "ForcedReset", "class_forced_reset.html", null ],
      [ "GreatArcStudios.PauseManager", "class_great_arc_studios_1_1_pause_manager.html", null ],
      [ "GreatArcStudios.Rotate", "class_great_arc_studios_1_1_rotate.html", null ],
      [ "HideUI", "class_hide_u_i.html", null ],
      [ "Inventory", "class_inventory.html", null ],
      [ "InventoryItem", "class_inventory_item.html", null ],
      [ "ItemClear", "class_item_clear.html", null ],
      [ "ItemTooltip", "class_item_tooltip.html", null ],
      [ "LightChange", "class_light_change.html", null ],
      [ "LoadSceneOnClick", "class_load_scene_on_click.html", null ],
      [ "MaterialChanger", "class_material_changer.html", null ],
      [ "MaterialChanger2", "class_material_changer2.html", null ],
      [ "MaterialChanger3", "class_material_changer3.html", null ],
      [ "MaterialChanger4", "class_material_changer4.html", null ],
      [ "Minimap", "class_minimap.html", null ],
      [ "MinimapIcon", "class_minimap_icon.html", null ],
      [ "Onhit", "class_onhit.html", null ],
      [ "PanelManager", "class_panel_manager.html", null ],
      [ "Pickup", "class_pickup.html", null ],
      [ "PlayerController", "class_player_controller.html", null ],
      [ "Pour", "class_pour.html", null ],
      [ "Puzzle2", "class_puzzle2.html", null ],
      [ "Puzzle2GasBag", "class_puzzle2_gas_bag.html", null ],
      [ "Puzzle3", "class_puzzle3.html", null ],
      [ "Puzzle3Door", "class_puzzle3_door.html", null ],
      [ "Puzzle3GasBag", "class_puzzle3_gas_bag.html", null ],
      [ "Puzzle3LD", "class_puzzle3_l_d.html", null ],
      [ "Puzzle_1_Door", "class_puzzle__1___door.html", null ],
      [ "Puzzle_2_Door", "class_puzzle__2___door.html", null ],
      [ "Puzzle_4_Door", "class_puzzle__4___door.html", null ],
      [ "PuzzleFourTable", "class_puzzle_four_table.html", null ],
      [ "PuzzleOneTable", "class_puzzle_one_table.html", null ],
      [ "PuzzleUI", "class_puzzle_u_i.html", null ],
      [ "QuitOnEsc", "class_quit_on_esc.html", null ],
      [ "RemoveFromInventory", "class_remove_from_inventory.html", null ],
      [ "ResizePanel", "class_resize_panel.html", null ],
      [ "RespawnFruit", "class_respawn_fruit.html", null ],
      [ "RespawnFruit2D", "class_respawn_fruit2_d.html", null ],
      [ "RotateGenerator", "class_rotate_generator.html", null ],
      [ "scr_camera", "classscr__camera.html", null ],
      [ "ScrollDetailTexture", "class_scroll_detail_texture.html", null ],
      [ "SecureClosetDoor", "class_secure_closet_door.html", null ],
      [ "SelectOnInput", "class_select_on_input.html", null ],
      [ "ShootDemo", "class_shoot_demo.html", null ],
      [ "ShootFruit", "class_shoot_fruit.html", null ],
      [ "ShowSliderValue", "class_show_slider_value.html", null ],
      [ "SlotController", "class_slot_controller.html", null ],
      [ "Teleporter", "class_teleporter.html", null ],
      [ "Test_Text", "class_test___text.html", null ],
      [ "TiltWindow", "class_tilt_window.html", null ],
      [ "timer", "classtimer.html", null ],
      [ "Tooltip", "class_tooltip.html", null ],
      [ "UnityStandardAssets.Characters.FirstPerson.FirstPersonController", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_first_person_controller.html", null ],
      [ "UnityStandardAssets.Characters.FirstPerson.HeadBob", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_head_bob.html", null ],
      [ "UnityStandardAssets.Characters.FirstPerson.RigidbodyFirstPersonController", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_rigidbody_first_person_controller.html", null ],
      [ "UnityStandardAssets.Characters.ThirdPerson.AICharacterControl", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_a_i_character_control.html", null ],
      [ "UnityStandardAssets.Characters.ThirdPerson.ThirdPersonCharacter", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_third_person_character.html", null ],
      [ "UnityStandardAssets.Characters.ThirdPerson.ThirdPersonUserControl", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_third_person_user_control.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.AxisTouchButton", "class_unity_standard_assets_1_1_cross_platform_input_1_1_axis_touch_button.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.ButtonHandler", "class_unity_standard_assets_1_1_cross_platform_input_1_1_button_handler.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.InputAxisScrollbar", "class_unity_standard_assets_1_1_cross_platform_input_1_1_input_axis_scrollbar.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.Joystick", "class_unity_standard_assets_1_1_cross_platform_input_1_1_joystick.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.MobileControlRig", "class_unity_standard_assets_1_1_cross_platform_input_1_1_mobile_control_rig.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.TiltInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_tilt_input.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.TouchPad", "class_unity_standard_assets_1_1_cross_platform_input_1_1_touch_pad.html", null ],
      [ "UnityStandardAssets.Effects.AfterburnerPhysicsForce", "class_unity_standard_assets_1_1_effects_1_1_afterburner_physics_force.html", null ],
      [ "UnityStandardAssets.Effects.ExplosionFireAndDebris", "class_unity_standard_assets_1_1_effects_1_1_explosion_fire_and_debris.html", null ],
      [ "UnityStandardAssets.Effects.ExplosionPhysicsForce", "class_unity_standard_assets_1_1_effects_1_1_explosion_physics_force.html", null ],
      [ "UnityStandardAssets.Effects.ExtinguishableParticleSystem", "class_unity_standard_assets_1_1_effects_1_1_extinguishable_particle_system.html", null ],
      [ "UnityStandardAssets.Effects.FireLight", "class_unity_standard_assets_1_1_effects_1_1_fire_light.html", null ],
      [ "UnityStandardAssets.Effects.Hose", "class_unity_standard_assets_1_1_effects_1_1_hose.html", null ],
      [ "UnityStandardAssets.Effects.ParticleSystemMultiplier", "class_unity_standard_assets_1_1_effects_1_1_particle_system_multiplier.html", null ],
      [ "UnityStandardAssets.Effects.SmokeParticles", "class_unity_standard_assets_1_1_effects_1_1_smoke_particles.html", null ],
      [ "UnityStandardAssets.Effects.WaterHoseParticles", "class_unity_standard_assets_1_1_effects_1_1_water_hose_particles.html", null ],
      [ "UnityStandardAssets.ImageEffects.Blur", "class_unity_standard_assets_1_1_image_effects_1_1_blur.html", null ],
      [ "UnityStandardAssets.ImageEffects.ContrastStretch", "class_unity_standard_assets_1_1_image_effects_1_1_contrast_stretch.html", null ],
      [ "UnityStandardAssets.ImageEffects.ImageEffectBase", "class_unity_standard_assets_1_1_image_effects_1_1_image_effect_base.html", [
        [ "UnityStandardAssets.ImageEffects.ColorCorrectionRamp", "class_unity_standard_assets_1_1_image_effects_1_1_color_correction_ramp.html", null ],
        [ "UnityStandardAssets.ImageEffects.Grayscale", "class_unity_standard_assets_1_1_image_effects_1_1_grayscale.html", null ],
        [ "UnityStandardAssets.ImageEffects.MotionBlur", "class_unity_standard_assets_1_1_image_effects_1_1_motion_blur.html", null ],
        [ "UnityStandardAssets.ImageEffects.SepiaTone", "class_unity_standard_assets_1_1_image_effects_1_1_sepia_tone.html", null ],
        [ "UnityStandardAssets.ImageEffects.Twirl", "class_unity_standard_assets_1_1_image_effects_1_1_twirl.html", null ],
        [ "UnityStandardAssets.ImageEffects.Vortex", "class_unity_standard_assets_1_1_image_effects_1_1_vortex.html", null ]
      ] ],
      [ "UnityStandardAssets.ImageEffects.NoiseAndScratches", "class_unity_standard_assets_1_1_image_effects_1_1_noise_and_scratches.html", null ],
      [ "UnityStandardAssets.ImageEffects.PostEffectsBase", "class_unity_standard_assets_1_1_image_effects_1_1_post_effects_base.html", [
        [ "UnityStandardAssets.ImageEffects.Antialiasing", "class_unity_standard_assets_1_1_image_effects_1_1_antialiasing.html", null ],
        [ "UnityStandardAssets.ImageEffects.Bloom", "class_unity_standard_assets_1_1_image_effects_1_1_bloom.html", null ],
        [ "UnityStandardAssets.ImageEffects.BloomAndFlares", "class_unity_standard_assets_1_1_image_effects_1_1_bloom_and_flares.html", null ],
        [ "UnityStandardAssets.ImageEffects.BloomOptimized", "class_unity_standard_assets_1_1_image_effects_1_1_bloom_optimized.html", null ],
        [ "UnityStandardAssets.ImageEffects.BlurOptimized", "class_unity_standard_assets_1_1_image_effects_1_1_blur_optimized.html", null ],
        [ "UnityStandardAssets.ImageEffects.CameraMotionBlur", "class_unity_standard_assets_1_1_image_effects_1_1_camera_motion_blur.html", null ],
        [ "UnityStandardAssets.ImageEffects.ColorCorrectionCurves", "class_unity_standard_assets_1_1_image_effects_1_1_color_correction_curves.html", null ],
        [ "UnityStandardAssets.ImageEffects.ColorCorrectionLookup", "class_unity_standard_assets_1_1_image_effects_1_1_color_correction_lookup.html", null ],
        [ "UnityStandardAssets.ImageEffects.ContrastEnhance", "class_unity_standard_assets_1_1_image_effects_1_1_contrast_enhance.html", null ],
        [ "UnityStandardAssets.ImageEffects.CreaseShading", "class_unity_standard_assets_1_1_image_effects_1_1_crease_shading.html", null ],
        [ "UnityStandardAssets.ImageEffects.DepthOfField", "class_unity_standard_assets_1_1_image_effects_1_1_depth_of_field.html", null ],
        [ "UnityStandardAssets.ImageEffects.DepthOfFieldDeprecated", "class_unity_standard_assets_1_1_image_effects_1_1_depth_of_field_deprecated.html", null ],
        [ "UnityStandardAssets.ImageEffects.EdgeDetection", "class_unity_standard_assets_1_1_image_effects_1_1_edge_detection.html", null ],
        [ "UnityStandardAssets.ImageEffects.Fisheye", "class_unity_standard_assets_1_1_image_effects_1_1_fisheye.html", null ],
        [ "UnityStandardAssets.ImageEffects.GlobalFog", "class_unity_standard_assets_1_1_image_effects_1_1_global_fog.html", null ],
        [ "UnityStandardAssets.ImageEffects.NoiseAndGrain", "class_unity_standard_assets_1_1_image_effects_1_1_noise_and_grain.html", null ],
        [ "UnityStandardAssets.ImageEffects.ScreenOverlay", "class_unity_standard_assets_1_1_image_effects_1_1_screen_overlay.html", null ],
        [ "UnityStandardAssets.ImageEffects.ScreenSpaceAmbientObscurance", "class_unity_standard_assets_1_1_image_effects_1_1_screen_space_ambient_obscurance.html", null ],
        [ "UnityStandardAssets.ImageEffects.SunShafts", "class_unity_standard_assets_1_1_image_effects_1_1_sun_shafts.html", null ],
        [ "UnityStandardAssets.ImageEffects.TiltShift", "class_unity_standard_assets_1_1_image_effects_1_1_tilt_shift.html", null ],
        [ "UnityStandardAssets.ImageEffects.Tonemapping", "class_unity_standard_assets_1_1_image_effects_1_1_tonemapping.html", null ],
        [ "UnityStandardAssets.ImageEffects.VignetteAndChromaticAberration", "class_unity_standard_assets_1_1_image_effects_1_1_vignette_and_chromatic_aberration.html", null ]
      ] ],
      [ "UnityStandardAssets.ImageEffects.PostEffectsHelper", "class_unity_standard_assets_1_1_image_effects_1_1_post_effects_helper.html", null ],
      [ "UnityStandardAssets.ImageEffects.ScreenSpaceAmbientOcclusion", "class_unity_standard_assets_1_1_image_effects_1_1_screen_space_ambient_occlusion.html", null ],
      [ "UnityStandardAssets.Utility.ActivateTrigger", "class_unity_standard_assets_1_1_utility_1_1_activate_trigger.html", null ],
      [ "UnityStandardAssets.Utility.AutoMobileShaderSwitch", "class_unity_standard_assets_1_1_utility_1_1_auto_mobile_shader_switch.html", null ],
      [ "UnityStandardAssets.Utility.AutoMoveAndRotate", "class_unity_standard_assets_1_1_utility_1_1_auto_move_and_rotate.html", null ],
      [ "UnityStandardAssets.Utility.DragRigidbody", "class_unity_standard_assets_1_1_utility_1_1_drag_rigidbody.html", null ],
      [ "UnityStandardAssets.Utility.DynamicShadowSettings", "class_unity_standard_assets_1_1_utility_1_1_dynamic_shadow_settings.html", null ],
      [ "UnityStandardAssets.Utility.FollowTarget", "class_unity_standard_assets_1_1_utility_1_1_follow_target.html", null ],
      [ "UnityStandardAssets.Utility.FPSCounter", "class_unity_standard_assets_1_1_utility_1_1_f_p_s_counter.html", null ],
      [ "UnityStandardAssets.Utility.ObjectResetter", "class_unity_standard_assets_1_1_utility_1_1_object_resetter.html", null ],
      [ "UnityStandardAssets.Utility.ParticleSystemDestroyer", "class_unity_standard_assets_1_1_utility_1_1_particle_system_destroyer.html", null ],
      [ "UnityStandardAssets.Utility.PlatformSpecificContent", "class_unity_standard_assets_1_1_utility_1_1_platform_specific_content.html", null ],
      [ "UnityStandardAssets.Utility.SimpleActivatorMenu", "class_unity_standard_assets_1_1_utility_1_1_simple_activator_menu.html", null ],
      [ "UnityStandardAssets.Utility.SimpleMouseRotator", "class_unity_standard_assets_1_1_utility_1_1_simple_mouse_rotator.html", null ],
      [ "UnityStandardAssets.Utility.SmoothFollow", "class_unity_standard_assets_1_1_utility_1_1_smooth_follow.html", null ],
      [ "UnityStandardAssets.Utility.TimedObjectActivator", "class_unity_standard_assets_1_1_utility_1_1_timed_object_activator.html", null ],
      [ "UnityStandardAssets.Utility.TimedObjectDestructor", "class_unity_standard_assets_1_1_utility_1_1_timed_object_destructor.html", null ],
      [ "UnityStandardAssets.Utility.WaypointCircuit", "class_unity_standard_assets_1_1_utility_1_1_waypoint_circuit.html", null ],
      [ "UnityStandardAssets.Utility.WaypointProgressTracker", "class_unity_standard_assets_1_1_utility_1_1_waypoint_progress_tracker.html", null ],
      [ "UnityStandardAssets.Vehicles.Ball.Ball", "class_unity_standard_assets_1_1_vehicles_1_1_ball_1_1_ball.html", null ],
      [ "UnityStandardAssets.Vehicles.Ball.BallUserControl", "class_unity_standard_assets_1_1_vehicles_1_1_ball_1_1_ball_user_control.html", null ]
    ] ],
    [ "UnityStandardAssets.Characters.FirstPerson.MouseLook", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_mouse_look.html", null ],
    [ "UnityStandardAssets.Characters.FirstPerson.RigidbodyFirstPersonController.MovementSettings", "class_unity_standard_assets_1_1_characters_1_1_first_person_1_1_rigidbody_first_person_controller_1_1_movement_settings.html", null ],
    [ "UnityStandardAssets.ImageEffects.Quads", "class_unity_standard_assets_1_1_image_effects_1_1_quads.html", null ],
    [ "UnityStandardAssets.Utility.AutoMobileShaderSwitch.ReplacementDefinition", "class_unity_standard_assets_1_1_utility_1_1_auto_mobile_shader_switch_1_1_replacement_definition.html", null ],
    [ "UnityStandardAssets.Utility.AutoMobileShaderSwitch.ReplacementList", "class_unity_standard_assets_1_1_utility_1_1_auto_mobile_shader_switch_1_1_replacement_list.html", null ],
    [ "UnityStandardAssets.Utility.WaypointCircuit.RoutePoint", "struct_unity_standard_assets_1_1_utility_1_1_waypoint_circuit_1_1_route_point.html", null ],
    [ "GreatArcStudios.SaveSettings", "class_great_arc_studios_1_1_save_settings.html", null ],
    [ "UnityStandardAssets.ImageEffects.Triangles", "class_unity_standard_assets_1_1_image_effects_1_1_triangles.html", null ],
    [ "UnityStandardAssets.Utility.AutoMoveAndRotate.Vector3andSpace", "class_unity_standard_assets_1_1_utility_1_1_auto_move_and_rotate_1_1_vector3and_space.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxis", "class_unity_standard_assets_1_1_cross_platform_input_1_1_cross_platform_input_manager_1_1_virtual_axis.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualButton", "class_unity_standard_assets_1_1_cross_platform_input_1_1_cross_platform_input_manager_1_1_virtual_button.html", null ],
    [ "UnityStandardAssets.CrossPlatformInput.VirtualInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_virtual_input.html", [
      [ "UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_mobile_input.html", null ],
      [ "UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput", "class_unity_standard_assets_1_1_cross_platform_input_1_1_platform_specific_1_1_standalone_input.html", null ]
    ] ],
    [ "UnityStandardAssets.Utility.WaypointCircuit.WaypointList", "class_unity_standard_assets_1_1_utility_1_1_waypoint_circuit_1_1_waypoint_list.html", null ]
];